### ISSUE TITLE
question about brd cmds

### ISSUE THREAD

**Issue by ozee** [neuromancerxi/ashitacast_xml_nocsouls#1]
I really don't know where else to post this question so I figured I might try your GH issues. I love what you have done with your BRD profile and have tailored some of it to fit my own (tyvm) but I was curious about one bit in your file. In each of the commands that you have created for the one-button spell casting you have something like `//valorminuet5` and I didn't know if that aliased something for you or if you purposefully omitted the actual `/ma <spell>` from the command. Do you have any insight into this? I'd be interested. Thanks!

**Comment by neuromancerxi** [comment]
FYI: General questions can be addressed in the NocSouls Discord #job_qa channel (see README.md).

Ashitacast allows for custom /commands. In this case it creates a command called `/minuet` which will roll through and check to see which spell it should cast based on variable checks, passing that to the client via a [shorthand](https://docs.ashitaxi.com/plugins/shorthand/) command (e.g. `//valorminuet5`) which is the equivalent of `/ma "Valor Minuet V" <me>`
